baseurl = "http://www.azert.co.uk"
disqusShortname = "azertsoftware"
googleAnalytics = "UA-91073756-1"
languageCode = "en-gb"
paginate = 20
sectionPagesMenu = "main"
theme = "hugo-minimalist-theme"
title = "Azert Software"
[[menu.main]]
identifier = "project"
name = "Projects"
url = "/project/"
weight = 0
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post"
weight = 1
[params]
avatar = "img/profile.jpg"
copyright = "Azert Software 2017"
custom_css = ["css/site.css"]
custom_js = []
google_analytics = "UA-91073756-1"
header_background = "img/Azert-Logo-White.png"
header_title = "Welcome to Azert Software"
location = "Northern Ireland"
site_author = "Mark Smith"
site_description = "Code, projects and research."
[social]
behance = ""
dribbble = ""
facebook = ""
github = "azert-software"
gplus = ""
instagram = ""
linkedin = ""
twitter = "azertsoftware"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
